### Preprocessing for model training(Steps included in Feature Engineering)

In [ ]:
dataset=pd.read_csv('Data/sample_data_intw.csv')
dataset.head()

In [ ]:
dataset.drop(['Unnamed: 0','msisdn','pcircle'],inplace=True, axis=1)

In [ ]:
dataset.head()

In [ ]:
dataset['pdate']=pd.to_datetime(dataset['pdate'])

In [ ]:
dataset['year'] = dataset['pdate'].dt.year

In [ ]:
dataset['month'] = dataset['pdate'].dt.month

In [ ]:
dataset['day'] = dataset['pdate'].dt.day

In [ ]:
dataset = dataset.drop(['year','pdate'], axis=1)

In [ ]:
#dataset.to_csv('Data/DataPreprocessBasic.csv',index=False) 

In [ ]:
scaling_feature=[feature for feature in dataset.columns if feature not in 'label']
scaling_feature

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(dataset[scaling_feature])

In [ ]:
scaler.transform(dataset[scaling_feature])

In [ ]:
# transform the train and test set, and add on the Id and SalePrice variables
data = pd.concat([dataset[['label']].reset_index(drop=True),
                    pd.DataFrame(scaler.transform(dataset[scaling_feature]), columns=scaling_feature)],
                    axis=1)

In [ ]:
data.head()

In [ ]:
#data.to_csv('Data/DataPreprocessedStdNorm.csv',index=False)

## Model Training 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
## Display all the columns of the dataframe

pd.pandas.set_option('display.max_columns',None)

In [2]:
dataset=pd.read_csv('Data/DataPreprocessBasic.csv')

In [30]:
from sklearn.model_selection import train_test_split
X_cols = [i for i in dataset.columns if i not in 'label']
X = dataset[X_cols]
y = dataset['label']
#X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

In [34]:
dataset.head()

label    aon  daily_decr30  daily_decr90  rental30  rental90  \
0      0  272.0   3055.050000   3065.150000    220.13    260.13   
1      1  712.0  12122.000000  12124.750000   3691.26   3691.26   
2      1  535.0   1398.000000   1398.000000    900.13    900.13   
3      1  241.0     21.228000     21.228000    159.42    159.42   
4      1  947.0    150.619333    150.619333   1098.90   1098.90   

   last_rech_date_ma  last_rech_date_da  last_rech_amt_ma  cnt_ma_rech30  \
0                2.0                0.0              1539              2   
1               20.0                0.0              5787              1   
2                3.0                0.0              1539              1   
3               41.0                0.0               947              0   
4                4.0                0.0              2309              7   

   fr_ma_rech30  sumamnt_ma_rech30  medianamnt_ma_rech30  \
0          21.0             3078.0                1539.0   
1           0.0             5787.0                5787.0   
2           0.0             1539.0                1539.0   
3           0.0                0.0                   0.0   
4           2.0            20029.0                2309.0   

   medianmarechprebal30  cnt_ma_rech90  fr_ma_rech90  sumamnt_ma_rech90  \
0                  7.50              2            21               3078   
1                 61.04              1             0               5787   
2                 66.32              1             0               1539   
3                  0.00              1             0                947   
4                 29.00              8             2              23496   

   medianamnt_ma_rech90  medianmarechprebal90  cnt_da_rech30  fr_da_rech30  \
0                1539.0                  7.50            0.0           0.0   
1                5787.0                 61.04            0.0           0.0   
2                1539.0                 66.32            0.0           0.0   
3                 947.0                  2.50            0.0           0.0   
4                2888.0                 35.00            0.0           0.0   

   cnt_da_rech90  fr_da_rech90  cnt_loans30  amnt_loans30  maxamnt_loans30  \
0              0             0            2            12              6.0   
1              0             0            1            12             12.0   
2              0             0            1             6              6.0   
3              0             0            2            12              6.0   
4              0             0            7            42              6.0   

   medianamnt_loans30  cnt_loans90  amnt_loans90  maxamnt_loans90  \
0                 0.0          2.0            12                6   
1                 0.0          1.0            12               12   
2                 0.0          1.0             6                6   
3                 0.0          2.0            12                6   
4                 0.0          7.0            42                6   

   medianamnt_loans90  payback30  payback90  month  day  
0                 0.0  29.000000  29.000000      7   20  
1                 0.0   0.000000   0.000000      8   10  
2                 0.0   0.000000   0.000000      8   19  
3                 0.0   0.000000   0.000000      6    6  
4                 0.0   2.333333   2.333333      6   22

### Training model on following algoritims:
1) Random Forest
<br>2) Ada Boost
<br>3) Gradient Boosting Classifier
<br>4) SVM 'RBF' kernel
<br>5) SVM Linear Kernel
<br>5) Logistic Regression
<br>6) XGBoost

### 1) Random Forest using Stratified Train Test Split

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)
print(len(X_train),len(X_test))

clf = RandomForestClassifier(random_state=0).fit(X_train,y_train)
y_classprop_predicted = clf.predict(X_test)
confusion = classification_report(y_test, y_classprop_predicted)
print(confusion)

157194 52399
              precision    recall  f1-score   support

           0       0.79      0.51      0.62      6541
           1       0.93      0.98      0.96     45858

    accuracy                           0.92     52399
   macro avg       0.86      0.75      0.79     52399
weighted avg       0.92      0.92      0.91     52399



### 2) AdaBoost Forest using Stratified Train Test Split

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

clf = AdaBoostClassifier(random_state=0).fit(X_train,y_train)
y_classprop_predicted = clf.predict(X_test)
confusion = classification_report(y_test, y_classprop_predicted)
print(confusion)

              precision    recall  f1-score   support

           0       0.78      0.41      0.54      6541
           1       0.92      0.98      0.95     45858

    accuracy                           0.91     52399
   macro avg       0.85      0.70      0.75     52399
weighted avg       0.90      0.91      0.90     52399



### 3) Gradient Bossting Classifier using Stratified Train Test Split

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

clf = GradientBoostingClassifier().fit(X_train,y_train)
y_classprop_predicted = clf.predict(X_test)
confusion = classification_report(y_test, y_classprop_predicted)
print(confusion)

              precision    recall  f1-score   support

           0       0.78      0.47      0.59      6541
           1       0.93      0.98      0.95     45858

    accuracy                           0.92     52399
   macro avg       0.86      0.73      0.77     52399
weighted avg       0.91      0.92      0.91     52399



### 4) SVM RBF Kernel using Normalized data

In [2]:
dataset=pd.read_csv('Data/DataPreprocessedStdNorm.csv')

In [4]:
from sklearn.model_selection import train_test_split
X_cols = [i for i in dataset.columns if i not in 'label']
X = dataset[X_cols]
y = dataset['label']

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

clf = SVC(kernel='rbf').fit(X_train,y_train)
y_classprop_predicted = clf.predict(X_test)
confusion = classification_report(y_test, y_classprop_predicted)
print(confusion)

              precision    recall  f1-score   support

           0       0.64      0.26      0.37      6541
           1       0.90      0.98      0.94     45858

    accuracy                           0.89     52399
   macro avg       0.77      0.62      0.66     52399
weighted avg       0.87      0.89      0.87     52399



### 5) SVM Linear Kernel using Normalized data

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

clf = LinearSVC().fit(X_train,y_train)
y_classprop_predicted = clf.predict(X_test)
confusion = classification_report(y_test, y_classprop_predicted)
print(confusion)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


              precision    recall  f1-score   support

           0       0.49      0.01      0.01      6541
           1       0.88      1.00      0.93     45858

    accuracy                           0.88     52399
   macro avg       0.68      0.50      0.47     52399
weighted avg       0.83      0.88      0.82     52399



### 6) Logistic Regression using Normalized data

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

clf = LogisticRegression().fit(X_train,y_train)
y_classprop_predicted = clf.predict(X_test)
confusion = classification_report(y_test, y_classprop_predicted)
print(confusion)

              precision    recall  f1-score   support

           0       0.64      0.02      0.03      6541
           1       0.88      1.00      0.93     45858

    accuracy                           0.88     52399
   macro avg       0.76      0.51      0.48     52399
weighted avg       0.85      0.88      0.82     52399



In [66]:
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV


X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)
model = XGBClassifier(scale_pos_weight=1).fit(X_train, y_train)
y_classprop_predicted = model.predict(X_test)
confusion = classification_report(y_test, y_classprop_predicted)
print(confusion)

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:892: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:46:29] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
              precision    recall  f1-score   support

           0       0.75      0.56      0.64      6541
           1       0.94      0.97      0.96     45858

    accuracy                           0.92     52399
   macro avg       0.84      0.77      0.80     52399
weighted avg       0.92      0.92      0.92     52399



In [ ]:
y_classprop_predicted = model.predict(X_test)
confusion = classification_report(y_test, y_classprop_predicted)
print(confusion)

### Hyperparameter Tuining for RandomForest
<br> Since Random Forest has the highest accuracy, we are going to perform hyperparameter tuining on RF

In [2]:
dataset=pd.read_csv('Data/DataPreprocessBasic.csv')

In [3]:
from sklearn.model_selection import train_test_split
X_cols = [i for i in dataset.columns if i not in 'label']
X = dataset[X_cols]
y = dataset['label']

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import RandomizedSearchCV
import numpy as np


# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]
# Method of selecting samples for training each tree

random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

clf = RandomForestClassifier(random_state=0)
rf_random = RandomizedSearchCV(estimator = clf, param_distributions = random_grid, verbose=2, random_state=42, n_jobs = -1,scoring='f1_macro')
rf_random.fit(X_train, y_train)
print(rf_random.best_params_)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed: 31.4min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed: 55.2min finished


{'n_estimators': 1000, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 25}


In [39]:
print(rf_random.best_estimator_)
print(rf_random.best_score_)
print(rf_random)

RandomForestClassifier(max_depth=25, max_features='sqrt', n_estimators=1000,
                       random_state=0)
0.7888925360755182
RandomizedSearchCV(estimator=RandomForestClassifier(random_state=0), n_jobs=-1,
                   param_distributions={'max_depth': [5, 10, 15, 20, 25, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000, 1100,
                                                         1200]},
                   random_state=42, scoring='f1_macro', verbose=2)


In [40]:
print(rf_random.best_score_)
best_est = rf_random.best_estimator_
y_pred=best_est.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7888925360755182
[[ 3318  3223]
 [  861 44997]]
0.9220595812897193
              precision    recall  f1-score   support

           0       0.79      0.51      0.62      6541
           1       0.93      0.98      0.96     45858

    accuracy                           0.92     52399
   macro avg       0.86      0.74      0.79     52399
weighted avg       0.92      0.92      0.91     52399



### Using Class Weight in Random Forest Classifier

In [50]:
class_weight=dict({0:10,1:1})

In [51]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=1000, min_samples_split= 2, min_samples_leaf= 1, max_features= 'sqrt', max_depth= 25, class_weight=class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 10, 1: 1}, max_depth=25,
                       max_features='sqrt', n_estimators=1000)

In [52]:
y_pred=classifier.predict(X_train)
print(confusion_matrix(y_train,y_pred))
print(accuracy_score(y_train,y_pred))
print(classification_report(y_train,y_pred))

[[ 19610     11]
 [  3212 134361]]
0.9794966729010013
              precision    recall  f1-score   support

           0       0.86      1.00      0.92     19621
           1       1.00      0.98      0.99    137573

    accuracy                           0.98    157194
   macro avg       0.93      0.99      0.96    157194
weighted avg       0.98      0.98      0.98    157194



In [53]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 3923  2618]
 [ 1740 44118]]
0.9168304738640051
              precision    recall  f1-score   support

           0       0.69      0.60      0.64      6541
           1       0.94      0.96      0.95     45858

    accuracy                           0.92     52399
   macro avg       0.82      0.78      0.80     52399
weighted avg       0.91      0.92      0.91     52399



## Using Imb Learn
<br>We are going to use open source library imb learn and perform various techniques to deal with imbalance data
<br>Some of techniques we are going to use are:
<br>1) UnderSampling
<br>2) OverSampling
<br>3) SMOTETomek

### 1) Under Sampling

In [67]:
dataset=pd.read_csv('Data/DataPreprocessBasic.csv')

In [68]:
from sklearn.model_selection import train_test_split
X_cols = [i for i in dataset.columns if i not in 'label']
X = dataset[X_cols]
y = dataset['label']

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

In [70]:
from collections import Counter
from imblearn.under_sampling import NearMiss
Counter(y_train)

Counter({1: 137573, 0: 19621})

In [71]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [72]:
from collections import Counter
from imblearn.under_sampling import NearMiss

ns=NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


The number of classes before fit Counter({1: 137573, 0: 19621})
The number of classes after fit Counter({1: 24526, 0: 19621})


In [73]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [74]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 5576   965]
 [33547 12311]]
0.34136147636405273
              precision    recall  f1-score   support

           0       0.14      0.85      0.24      6541
           1       0.93      0.27      0.42     45858

    accuracy                           0.34     52399
   macro avg       0.53      0.56      0.33     52399
weighted avg       0.83      0.34      0.39     52399



### 2) SMOTETomek

In [ ]:
from imblearn.combine import SMOTETomek

In [ ]:
os=SMOTETomek(0.75)
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

### 3) Over Sampling

In [1]:
from imblearn.over_sampling import RandomOverSampler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import RandomizedSearchCV
from collections import Counter
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv('Data/DataPreprocessBasic.csv')

In [3]:
from sklearn.model_selection import train_test_split
X_cols = [i for i in dataset.columns if i not in 'label']
X = dataset[X_cols]
y = dataset['label']

In [12]:
#X_train, X_testCV, y_train, y_testCV = train_test_split(X, y, stratify=y, test_size=0.1)

In [6]:
os=RandomOverSampler(0.75)
X_train_ns,y_train_ns=os.fit_sample(X,y)
print("The number of classes before fit {}".format(Counter(y)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({1: 183431, 0: 26162})
The number of classes after fit Counter({1: 183431, 0: 137573})


In [28]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=4, shuffle=True, random_state=1)
for train_index, test_index in skf.split(X_train_ns, y_train_ns):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X_train_ns.iloc[list(train_index)], X_train_ns.iloc[list(test_index)]
    y_train, y_test = y_train_ns.iloc[list(train_index)], y_train_ns.iloc[list(test_index)]
    classifier=RandomForestClassifier(max_depth=20)
    classifier.fit(X_train,y_train)
    y_pred=classifier.predict(X_test)
    print(classification_report(y_test,y_pred))

TRAIN: [     0      1      3 ... 321000 321001 321003] TEST: [     2      4      6 ... 320996 320997 321002]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95     34394
           1       0.98      0.94      0.96     45857

    accuracy                           0.96     80251
   macro avg       0.95      0.96      0.96     80251
weighted avg       0.96      0.96      0.96     80251

TRAIN: [     1      2      3 ... 321000 321002 321003] TEST: [     0     10     22 ... 320984 320994 321001]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95     34393
           1       0.99      0.94      0.96     45858

    accuracy                           0.96     80251
   macro avg       0.95      0.96      0.96     80251
weighted avg       0.96      0.96      0.96     80251

TRAIN: [     0      1      2 ... 321001 321002 321003] TEST: [     3      5      7 ... 320991 320992 320999]
              preci

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, shuffle=True)

In [5]:
os=RandomOverSampler(0.75)
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


The number of classes before fit Counter({1: 165067, 0: 23566})
The number of classes after fit Counter({1: 165067, 0: 123800})


In [6]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(max_depth=20)
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier(max_depth=20)

In [7]:
y_pred=classifier.predict(X_train)
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.99      0.88     23566
           1       1.00      0.96      0.98    165067

    accuracy                           0.97    188633
   macro avg       0.90      0.98      0.93    188633
weighted avg       0.97      0.97      0.97    188633



In [8]:
y_pred=classifier.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.63      0.69      0.66      2596
           1       0.96      0.94      0.95     18364

    accuracy                           0.91     20960
   macro avg       0.79      0.82      0.81     20960
weighted avg       0.92      0.91      0.91     20960



In [11]:
classifier.predict_proba(X_test)

array([[1.60436328e-02, 9.83956367e-01],
       [1.60009120e-02, 9.83999088e-01],
       [2.63372292e-01, 7.36627708e-01],
       ...,
       [0.00000000e+00, 1.00000000e+00],
       [1.62601626e-04, 9.99837398e-01],
       [5.52241436e-02, 9.44775856e-01]])

In [89]:
from sklearn import metrics
metrics.roc_curve(y_test, y_pred)

(array([0.        , 0.32670845, 1.        ]),
 array([0.        , 0.94897292, 1.        ]),
 array([2, 1, 0], dtype=int64))

In [10]:
import pickle
pickle.dump(classifier, open('model.pkl','wb'))

In [12]:
model = pickle.load(open('model.pkl','rb'))